const SWIMMER_1_SKILLS: string[] = [
	'Enter and exit shallow water',
	'Jump into chest deep water',
	'Jump into water wearing PFD',
	'Tread water 30 sec. wearing PFD',
	'Hold breath underwater 5 sec.',
	'Submerge and Exhale 5 times',
	'Open eyes underwater',
	'Float on Front 5 sec.',
	'Float on Back 5 sec.',
	'Roll front to back and back to front',
	'Glide on front 3 m',
	'Glide on back 3 m',
	'Glide on side 3 m',
	'Flutter kick on front 5 m',
	'Flutter kick on back 5 m',
	'Front crawl 5 m wearing PFD',
	'Water smart message: Swim with a buddy',
	'Water smart message: Wear a lifejacket',
	'Water smart message: Check the Ice',
	'Water smart message: Swim to survive',
];

const SWIMMER_2_SKILLS: string[] = [
	'Jump into deep water, return and exit',
	'Sideways entry wearing PFD',
	'Tread water 15 sec.',
	'Recover object from bottom in chest deep water',
	'Wearing PFD jump into deep water tread 30 sec. and swim/kick 15m',
	'Flutter kick on front 10 m',
	'Flutter kick on back 10 m',
	'Flutter kick on side 10 m',
	'Whip kick in vertical position 30 sec. with aid',
	'Front crawl 10 m',
	'Back crawl 10 m',
	'Interval training 4x5m flutter kick with 20s rests',
	'Water smart message: Swim with a buddy',
	'Water smart message: Wear a lifejacket',
	'Water smart message: Check the Ice',
	'Water smart message: Swim to survive',
];

const SWIMMER_3_SKILLS: string[] = [
	'Kneeling dive into deep water',
	'Forward roll entry into deep water',
	'Tread water 30 sec.',
	'Handstand in shallow water',
	'Front somersault (in water)',
	'Jump into deep water, tread 30 sec., and swim/kick 25m',
	'Flutter kick on back 5 m; reverse direction and flutter kick on front 5 m',
	'Flutter kick on front 5 m; reverse direction and flutter kick on back 5 m',
	'Whip kick on back 10 m',
	'Front crawl 15 m',
	'Back crawl 15 m',
	'Interval training: 4 x 15 m flutter kick with 20 sec. rests',
	'Water smart message: Swim with a buddy',
	'Water smart message: Wear a lifejacket',
	'Water smart message: Check the Ice',
	'Water smart message: Swim to survive',
];

const SWIMMER_4_SKILLS: string[] = [
	'Standing dive into deep water',
	'Tread water 1 min.',
	'Swim underwater 5 m',
	'Canadian Swim to Survive Standard: Roll entry into deep water, tread 1 min. and swim 50 m',
	'Whip kick on front 15 m',
	'Breaststroke arms drill 15 m',
	'Front crawl 25 m',
	'Back crawl 25 m',
	'Interval training: 4 x 25 m front or back crawl with 20 sec. rests',
	'Sprint front crawl 25 m',
	'Water smart message: Swim with a buddy',
	'Water smart message: Wear a lifejacket',
	'Water smart message: Check the Ice',
	'Water smart message: Swim to survive',
];

const SWIMMER_5_SKILLS: string[] = [
	'Shallow dive into deep water',
	'Tuck jump (cannonball) into deep water',
	'Jump entry into deep water, and tread 2 min.',
	'Stationary eggbeater kick 30 sec.',
	'Back somersault (in water)',
	'Roll entry into deep water, tread 90 sec. and swim 75 m',
	'Breaststroke 25 m',
	'Front crawl 50 m',
	'Back crawl 50 m',
	'Head-up front crawl 10 m',
	'Interval training: 4 x 50 m front or back crawl with 30 sec. rests',
	'Interval training: 4 x 15 m breaststroke with 30 sec. rests',
	'Sprint front crawl 25 m',
	'Sprint back crawl 25 m',
	'Water smart message: Swim with a buddy',
	'Water smart message: Wear a lifejacket',
	'Water smart message: Check the Ice',
	'Water smart message: Swim to survive',
];

const SWIMMER_6_SKILLS: string[] = [
	'Stride entry into deep water',
	'Compact jump into deep water',
	'Legs-only surface support 45 sec.',
	'Swim underwater 10 m to recover object',
	'Eggbeater kick on back 15 m',
	'Scissor kick 15 m',
	'Breaststroke 50 m',
	'Front crawl 100 m',
	'Back crawl 100 m',
	'Head-up swim 25 m',
	'Interval training: 4 x 25 m breaststroke with 30 sec. rests',
	'Sprint breaststroke 25 m',
	'Workout 300 m',
	'Water smart message: Swim with a buddy',
	'Water smart message: Wear a lifejacket',
	'Water smart message: Check the Ice',
	'Water smart message: Swim to survive',
];

const SWIMMER_SKILLS = {
	SWIMMER_1: SWIMMER_1_SKILLS,
	SWIMMER_2: SWIMMER_2_SKILLS,
	SWIMMER_3: SWIMMER_3_SKILLS,
	SWIMMER_4: SWIMMER_4_SKILLS,
	SWIMMER_5: SWIMMER_5_SKILLS,
	SWIMMER_6: SWIMMER_6_SKILLS,
};

export default SWIMMER_SKILLS;
