const NAMES: string[] = [
    'Dayne Dellaire',
    'Hannah Catterall',
    'Bianca Addorisio',
    'Adam Schumacher',
    'Greg Papa',
    'Keira McGrath',
    'Caitlyn Freeman',
    'Susannah Freeman',
    'Julia Addorisio',
    'Ben Skinner',
    'Adam Skinner',
    'Alex Ashtonchewitz',
    'Alex Haines',
    'Alexander Ashton',
    'Matthew Cheron',
    'Jaime Bell',
    'Mat Monaco',
    'Julia Bell',
    'Matt Aiken',
    'Nathan Ferry',
    'Niko Julsing',
    'Mitch Coello',
    'Mitch Nullay',
    'Savannah Something',
    'Shelby Misreelal',
    'Alexis Gobin',
    'Anthony Ham',
    'Jeremy Something',
    'Liam Skinner',
    'Joseph Gato',
    'Nathan Instructor',
    'Emma Stanbridge',
    'Peyton Meddings',
]

export default NAMES;